site_name: Penetration Testing Guide
site_url: https://oxr463.github.io/pentesting-guide
site_description: Utilizing FOSS for profit.

site_author: Lucas Ramage

theme:
  name: gitbook

nav:
    - Home: index.md
    - Getting Started:
        - Tools: setup.md
    - Testing:
        - Information Gathering: information_gathering.md
        - Configuration and Deploy Management: configuration_management.md
        - Identity Management: identity_management.md
        - Authentication: authentication.md
        - Authorization: authorization.md
        - Session Management: session_management.md
        - Data Validation: data_validation.md
        - Error Handling: error_handling.md
        - Cryptography: cryptography.md
        - Business Logic: business_logic.md
        - Client Side: client_side.md
        - Mobile: mobile.md

docs_dir: content

plugins: 
  - cordova

extra:
  license: CC-BY-4.0
  platform: ['android']
  package_name: oxr463.pentesting.guide
  version: 0.0.1

repo_name: oxr463/pentesting-guide
repo_url: https://github.com/oxr463/pentesting-guide.git
remote_branch: master
