site_name: Penetration Testing Guide
site_url: https://oxr463.github.io/pentesting-guide
site_description: Utilizing FOSS for profit.

site_author: Lucas Ramage

theme:
  name: gitbook

docs_dir: content

plugins: []

repo_name: oxr463/pentesting-guide
repo_url: https://github.com/oxr463/pentesting-guide.git
remote_branch: master
