name: "Apache Cordova"

on:
  push: {branches: master}
  pull_request: {branches: master}
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use oxr463/setup-cordova
      uses: ./
      with:
        cordova_exec: |
          apk update && apk upgrade && \
          apk add python py3-pip && \
          pip install -r requirements.txt
          mkdocs build

